module.exports = {table:
{
  "*[AND,inlineShapeNot]" : {
     "AND": ["[AND,inlineShapeNot]","*[AND,inlineShapeNot]"], 
     "OR": [], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*[AND,shapeNot]" : {
     "AND": ["[AND,shapeNot]","*[AND,shapeNot]"], 
     "OR": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*[OR,inlineShapeAnd]" : {
     "OR": ["[OR,inlineShapeAnd]","*[OR,inlineShapeAnd]"], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*[OR,shapeAnd]" : {
     "OR": ["[OR,shapeAnd]","*[OR,shapeAnd]"], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*[unaryTripleExpr,;]" : {
     "$": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "(": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "&": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "RDF_TYPE": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "^": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "IRI_REF": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "PNAME_LN": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     "PNAME_NS": ["[unaryTripleExpr,;]","*[unaryTripleExpr,;]"], 
     ")": [], 
     "}": []}, 
  "*annotation" : {
     "//": ["annotation","*annotation"], 
     "%": [], 
     "OR": [], 
     "AND": [], 
     "IRI": [], 
     "BNODE": [], 
     "NONLITERAL": [], 
     "REGEXP": [], 
     "LENGTH": [], 
     "MINLENGTH": [], 
     "MAXLENGTH": [], 
     ";": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*codeDecl" : {
     "%": ["codeDecl","*codeDecl"], 
     "OR": [], 
     "AND": [], 
     "IRI": [], 
     "BNODE": [], 
     "NONLITERAL": [], 
     "REGEXP": [], 
     "LENGTH": [], 
     "MINLENGTH": [], 
     "MAXLENGTH": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     ")": [], 
     "$": []}, 
  "*directive" : {
     "BASE": ["directive","*directive"], 
     "PREFIX": ["directive","*directive"], 
     "IMPORT": ["directive","*directive"], 
     "$": [], 
     "start": [], 
     "%": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": []}, 
  "*exclusion" : {
     "-": ["exclusion","*exclusion"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "*languageExclusion" : {
     ".": ["languageExclusion","*languageExclusion"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "*literalExclusion" : {
     ".": ["literalExclusion","*literalExclusion"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "*numericFacet" : {
     "MININCLUSIVE": ["numericFacet","*numericFacet"], 
     "MINEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXINCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "TOTALDIGITS": ["numericFacet","*numericFacet"], 
     "FRACTIONDIGITS": ["numericFacet","*numericFacet"], 
     "OR": [], 
     "AND": [], 
     ")": [], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*or([extraPropertySet,CLOSED])" : {
     "CLOSED": ["or([extraPropertySet,CLOSED])","*or([extraPropertySet,CLOSED])"], 
     "EXTRA": ["or([extraPropertySet,CLOSED])","*or([extraPropertySet,CLOSED])"], 
     "{": []}, 
  "*predicate" : {
     "RDF_TYPE": ["predicate","*predicate"], 
     "IRI_REF": ["predicate","*predicate"], 
     "PNAME_LN": ["predicate","*predicate"], 
     "PNAME_NS": ["predicate","*predicate"], 
     "CLOSED": [], 
     "EXTRA": [], 
     "{": []}, 
  "*statement" : {
     "BASE": ["statement","*statement"], 
     "PREFIX": ["statement","*statement"], 
     "IMPORT": ["statement","*statement"], 
     "start": ["statement","*statement"], 
     "IRI_REF": ["statement","*statement"], 
     "BLANK_NODE_LABEL": ["statement","*statement"], 
     "PNAME_LN": ["statement","*statement"], 
     "PNAME_NS": ["statement","*statement"], 
     "$": []}, 
  "*stringFacet" : {
     "REGEXP": ["stringFacet","*stringFacet"], 
     "LENGTH": ["stringFacet","*stringFacet"], 
     "MINLENGTH": ["stringFacet","*stringFacet"], 
     "MAXLENGTH": ["stringFacet","*stringFacet"], 
     "OR": [], 
     "AND": [], 
     "{": [], 
     "CLOSED": [], 
     "ATPNAME_LN": [], 
     "ATPNAME_NS": [], 
     "@": [], 
     "EXTRA": [], 
     ")": [], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "*valueSetValue" : {
     "LANGTAG": ["valueSetValue","*valueSetValue"], 
     "@": ["valueSetValue","*valueSetValue"], 
     "IRI_REF": ["valueSetValue","*valueSetValue"], 
     "PNAME_LN": ["valueSetValue","*valueSetValue"], 
     "PNAME_NS": ["valueSetValue","*valueSetValue"], 
     "INTEGER": ["valueSetValue","*valueSetValue"], 
     "DECIMAL": ["valueSetValue","*valueSetValue"], 
     "DOUBLE": ["valueSetValue","*valueSetValue"], 
     "true": ["valueSetValue","*valueSetValue"], 
     "false": ["valueSetValue","*valueSetValue"], 
     "LANG_STRING_LITERAL1": ["valueSetValue","*valueSetValue"], 
     "LANG_STRING_LITERAL_LONG1": ["valueSetValue","*valueSetValue"], 
     "LANG_STRING_LITERAL2": ["valueSetValue","*valueSetValue"], 
     "LANG_STRING_LITERAL_LONG2": ["valueSetValue","*valueSetValue"], 
     "STRING_LITERAL1": ["valueSetValue","*valueSetValue"], 
     "STRING_LITERAL_LONG1": ["valueSetValue","*valueSetValue"], 
     "STRING_LITERAL2": ["valueSetValue","*valueSetValue"], 
     "STRING_LITERAL_LONG2": ["valueSetValue","*valueSetValue"], 
     "]": []}, 
  "*xsFacet" : {
     "REGEXP": ["xsFacet","*xsFacet"], 
     "LENGTH": ["xsFacet","*xsFacet"], 
     "MINLENGTH": ["xsFacet","*xsFacet"], 
     "MAXLENGTH": ["xsFacet","*xsFacet"], 
     "MININCLUSIVE": ["xsFacet","*xsFacet"], 
     "MINEXCLUSIVE": ["xsFacet","*xsFacet"], 
     "MAXINCLUSIVE": ["xsFacet","*xsFacet"], 
     "MAXEXCLUSIVE": ["xsFacet","*xsFacet"], 
     "TOTALDIGITS": ["xsFacet","*xsFacet"], 
     "FRACTIONDIGITS": ["xsFacet","*xsFacet"], 
     "OR": [], 
     "AND": [], 
     ")": [], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "+codeDecl" : {
     "%": ["codeDecl","*codeDecl"]}, 
  "+numericFacet" : {
     "MININCLUSIVE": ["numericFacet","*numericFacet"], 
     "MINEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXINCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "TOTALDIGITS": ["numericFacet","*numericFacet"], 
     "FRACTIONDIGITS": ["numericFacet","*numericFacet"]}, 
  "+predicate" : {
     "RDF_TYPE": ["predicate","*predicate"], 
     "IRI_REF": ["predicate","*predicate"], 
     "PNAME_LN": ["predicate","*predicate"], 
     "PNAME_NS": ["predicate","*predicate"]}, 
  "+stringFacet" : {
     "REGEXP": ["stringFacet","*stringFacet"], 
     "LENGTH": ["stringFacet","*stringFacet"], 
     "MINLENGTH": ["stringFacet","*stringFacet"], 
     "MAXLENGTH": ["stringFacet","*stringFacet"]}, 
  "?NOT" : {
     "NOT": ["NOT"], 
     "(": [], 
     ".": [], 
     "LITERAL": [], 
     "IRI": [], 
     "BNODE": [], 
     "NONLITERAL": [], 
     "REGEXP": [], 
     "[": [], 
     "{": [], 
     "CLOSED": [], 
     "ATPNAME_LN": [], 
     "ATPNAME_NS": [], 
     "@": [], 
     "LENGTH": [], 
     "MINLENGTH": [], 
     "MAXLENGTH": [], 
     "IRI_REF": [], 
     "MININCLUSIVE": [], 
     "MINEXCLUSIVE": [], 
     "MAXINCLUSIVE": [], 
     "MAXEXCLUSIVE": [], 
     "TOTALDIGITS": [], 
     "FRACTIONDIGITS": [], 
     "EXTRA": [], 
     "PNAME_LN": [], 
     "PNAME_NS": []}, 
  "?[$,tripleExprLabel]" : {
     "$": ["[$,tripleExprLabel]"], 
     "(": [], 
     "RDF_TYPE": [], 
     "^": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": []}, 
  "?[^^,datatype]" : {
     "^^": ["[^^,datatype]"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "~": [], 
     "]": [], 
     "//": [], 
     "-": [], 
     "%": [], 
     "OR": [], 
     "AND": [], 
     "IRI": [], 
     "BNODE": [], 
     "NONLITERAL": [], 
     "REGEXP": [], 
     "LENGTH": [], 
     "MINLENGTH": [], 
     "MAXLENGTH": [], 
     ";": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "BLANK_NODE_LABEL": [], 
     "$": []}, 
  "?[or([notStartAction,startActions]),*statement]" : {
     "start": ["[or([notStartAction,startActions]),*statement]"], 
     "%": ["[or([notStartAction,startActions]),*statement]"], 
     "IRI_REF": ["[or([notStartAction,startActions]),*statement]"], 
     "BLANK_NODE_LABEL": ["[or([notStartAction,startActions]),*statement]"], 
     "PNAME_LN": ["[or([notStartAction,startActions]),*statement]"], 
     "PNAME_NS": ["[or([notStartAction,startActions]),*statement]"], 
     "$": []}, 
  "?[~,*exclusion]" : {
     "~": ["[~,*exclusion]"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "?[~,*languageExclusion]" : {
     "~": ["[~,*languageExclusion]"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "?[~,*literalExclusion]" : {
     "~": ["[~,*literalExclusion]"], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "?cardinality" : {
     "*": ["cardinality"], 
     "+": ["cardinality"], 
     "?": ["cardinality"], 
     "REPEAT_RANGE": ["cardinality"], 
     "%": [], 
     "//": [], 
     ";": []}, 
  "?inlineShapeOrRef" : {
     "{": ["inlineShapeOrRef"], 
     "CLOSED": ["inlineShapeOrRef"], 
     "ATPNAME_LN": ["inlineShapeOrRef"], 
     "ATPNAME_NS": ["inlineShapeOrRef"], 
     "@": ["inlineShapeOrRef"], 
     "EXTRA": ["inlineShapeOrRef"], 
     "OR": [], 
     "AND": [], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "?nonLitNodeConstraint" : {
     "IRI": ["nonLitNodeConstraint"], 
     "BNODE": ["nonLitNodeConstraint"], 
     "NONLITERAL": ["nonLitNodeConstraint"], 
     "REGEXP": ["nonLitNodeConstraint"], 
     "LENGTH": ["nonLitNodeConstraint"], 
     "MINLENGTH": ["nonLitNodeConstraint"], 
     "MAXLENGTH": ["nonLitNodeConstraint"], 
     "OR": [], 
     "AND": [], 
     ")": [], 
     "%": [], 
     "//": [], 
     "*": [], 
     "+": [], 
     "?": [], 
     "REPEAT_RANGE": [], 
     ";": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "?senseFlags" : {
     "^": ["senseFlags"], 
     "RDF_TYPE": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": []}, 
  "?shapeOrRef" : {
     "{": ["shapeOrRef"], 
     "CLOSED": ["shapeOrRef"], 
     "ATPNAME_LN": ["shapeOrRef"], 
     "ATPNAME_NS": ["shapeOrRef"], 
     "@": ["shapeOrRef"], 
     "EXTRA": ["shapeOrRef"], 
     "OR": [], 
     "AND": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "start": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "$": []}, 
  "?tripleExpression" : {
     "$": ["tripleExpression"], 
     "(": ["tripleExpression"], 
     "&": ["tripleExpression"], 
     "RDF_TYPE": ["tripleExpression"], 
     "^": ["tripleExpression"], 
     "IRI_REF": ["tripleExpression"], 
     "PNAME_LN": ["tripleExpression"], 
     "PNAME_NS": ["tripleExpression"], 
     "}": []}, 
  "?~" : {
     "~": ["~"], 
     "-": [], 
     "LANGTAG": [], 
     "@": [], 
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "LANG_STRING_LITERAL1": [], 
     "LANG_STRING_LITERAL_LONG1": [], 
     "LANG_STRING_LITERAL2": [], 
     "LANG_STRING_LITERAL_LONG2": [], 
     "STRING_LITERAL1": [], 
     "STRING_LITERAL_LONG1": [], 
     "STRING_LITERAL2": [], 
     "STRING_LITERAL_LONG2": [], 
     "]": []}, 
  "[$,tripleExprLabel]" : {
     "$": ["$","tripleExprLabel"]}, 
  "[AND,inlineShapeNot]" : {
     "AND": ["AND","inlineShapeNot"]}, 
  "[AND,shapeNot]" : {
     "AND": ["AND","shapeNot"]}, 
  "[OR,inlineShapeAnd]" : {
     "OR": ["OR","inlineShapeAnd"]}, 
  "[OR,shapeAnd]" : {
     "OR": ["OR","shapeAnd"]}, 
  "[^^,datatype]" : {
     "^^": ["^^","datatype"]}, 
  "[or([notStartAction,startActions]),*statement]" : {
     "start": ["or([notStartAction,startActions])","*statement"], 
     "%": ["or([notStartAction,startActions])","*statement"], 
     "IRI_REF": ["or([notStartAction,startActions])","*statement"], 
     "BLANK_NODE_LABEL": ["or([notStartAction,startActions])","*statement"], 
     "PNAME_LN": ["or([notStartAction,startActions])","*statement"], 
     "PNAME_NS": ["or([notStartAction,startActions])","*statement"]}, 
  "[string,?[^^,datatype]]" : {
     "STRING_LITERAL1": ["string","?[^^,datatype]"], 
     "STRING_LITERAL_LONG1": ["string","?[^^,datatype]"], 
     "STRING_LITERAL2": ["string","?[^^,datatype]"], 
     "STRING_LITERAL_LONG2": ["string","?[^^,datatype]"]}, 
  "[unaryTripleExpr,;]" : {
     "$": ["unaryTripleExpr",";"], 
     "(": ["unaryTripleExpr",";"], 
     "&": ["unaryTripleExpr",";"], 
     "RDF_TYPE": ["unaryTripleExpr",";"], 
     "^": ["unaryTripleExpr",";"], 
     "IRI_REF": ["unaryTripleExpr",";"], 
     "PNAME_LN": ["unaryTripleExpr",";"], 
     "PNAME_NS": ["unaryTripleExpr",";"]}, 
  "[~,*exclusion]" : {
     "~": ["~","*exclusion"]}, 
  "[~,*languageExclusion]" : {
     "~": ["~","*languageExclusion"]}, 
  "[~,*literalExclusion]" : {
     "~": ["~","*literalExclusion"]}, 
  "annotation" : {
     "//": ["//","predicate","or([iri,literal])"]}, 
  "baseDecl" : {
     "BASE": ["BASE","IRI_REF"]}, 
  "blankNode" : {
     "BLANK_NODE_LABEL": ["BLANK_NODE_LABEL"]}, 
  "booleanLiteral" : {
     "true": ["or([true,false])"], 
     "false": ["or([true,false])"]}, 
  "bracketedTripleExpr" : {
     "(": ["(","tripleExpression",")","?cardinality","*annotation","semanticActions"]}, 
  "cardinality" : {
     "*": ["*"], 
     "+": ["+"], 
     "?": ["?"], 
     "REPEAT_RANGE": ["REPEAT_RANGE"]}, 
  "codeDecl" : {
     "%": ["%","iri","or([CODE,%])"]}, 
  "datatype" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"]}, 
  "directive" : {
     "BASE": ["or([baseDecl,prefixDecl,importDecl])"], 
     "PREFIX": ["or([baseDecl,prefixDecl,importDecl])"], 
     "IMPORT": ["or([baseDecl,prefixDecl,importDecl])"]}, 
  "elementGroup" : {
     "$": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "(": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "&": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "RDF_TYPE": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "^": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "IRI_REF": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "PNAME_LN": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"], 
     "PNAME_NS": ["unaryTripleExpr",";","*[unaryTripleExpr,;]"]}, 
  "exclusion" : {
     "-": ["-","or([iri,literal,LANGTAG])","?~"]}, 
  "extraPropertySet" : {
     "EXTRA": ["EXTRA","+predicate"]}, 
  "groupTripleExpr" : {
     "$": ["elementGroup"], 
     "(": ["elementGroup"], 
     "&": ["elementGroup"], 
     "RDF_TYPE": ["elementGroup"], 
     "^": ["elementGroup"], 
     "IRI_REF": ["elementGroup"], 
     "PNAME_LN": ["elementGroup"], 
     "PNAME_NS": ["elementGroup"]}, 
  "importDecl" : {
     "IMPORT": ["IMPORT","IRI_REF"]}, 
  "include" : {
     "&": ["&","tripleExprLabel"]}, 
  "inlineShapeAnd" : {
     "NOT": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "(": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     ".": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "LITERAL": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "IRI": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "BNODE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "NONLITERAL": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "REGEXP": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "[": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "{": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "CLOSED": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "ATPNAME_LN": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "ATPNAME_NS": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "@": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "LENGTH": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MINLENGTH": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MAXLENGTH": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "IRI_REF": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MININCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MINEXCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MAXINCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MAXEXCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "TOTALDIGITS": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "FRACTIONDIGITS": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "EXTRA": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "PNAME_LN": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "PNAME_NS": ["inlineShapeNot","*[AND,inlineShapeNot]"]}, 
  "inlineShapeAtom" : {
     "IRI": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "BNODE": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "NONLITERAL": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "REGEXP": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "LENGTH": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "MINLENGTH": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "MAXLENGTH": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "LITERAL": ["litNodeConstraint"], 
     "[": ["litNodeConstraint"], 
     "IRI_REF": ["litNodeConstraint"], 
     "MININCLUSIVE": ["litNodeConstraint"], 
     "MINEXCLUSIVE": ["litNodeConstraint"], 
     "MAXINCLUSIVE": ["litNodeConstraint"], 
     "MAXEXCLUSIVE": ["litNodeConstraint"], 
     "TOTALDIGITS": ["litNodeConstraint"], 
     "FRACTIONDIGITS": ["litNodeConstraint"], 
     "PNAME_LN": ["litNodeConstraint"], 
     "PNAME_NS": ["litNodeConstraint"], 
     "{": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "CLOSED": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_LN": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_NS": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "@": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "EXTRA": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "(": ["(","shapeExpression",")"], 
     ".": ["."]}, 
  "inlineShapeDefinition" : {
     "{": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}"], 
     "CLOSED": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}"], 
     "EXTRA": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}"]}, 
  "inlineShapeExpression" : {
     "NOT": ["inlineShapeOr"], 
     "(": ["inlineShapeOr"], 
     ".": ["inlineShapeOr"], 
     "LITERAL": ["inlineShapeOr"], 
     "IRI": ["inlineShapeOr"], 
     "BNODE": ["inlineShapeOr"], 
     "NONLITERAL": ["inlineShapeOr"], 
     "REGEXP": ["inlineShapeOr"], 
     "[": ["inlineShapeOr"], 
     "{": ["inlineShapeOr"], 
     "CLOSED": ["inlineShapeOr"], 
     "ATPNAME_LN": ["inlineShapeOr"], 
     "ATPNAME_NS": ["inlineShapeOr"], 
     "@": ["inlineShapeOr"], 
     "LENGTH": ["inlineShapeOr"], 
     "MINLENGTH": ["inlineShapeOr"], 
     "MAXLENGTH": ["inlineShapeOr"], 
     "IRI_REF": ["inlineShapeOr"], 
     "MININCLUSIVE": ["inlineShapeOr"], 
     "MINEXCLUSIVE": ["inlineShapeOr"], 
     "MAXINCLUSIVE": ["inlineShapeOr"], 
     "MAXEXCLUSIVE": ["inlineShapeOr"], 
     "TOTALDIGITS": ["inlineShapeOr"], 
     "FRACTIONDIGITS": ["inlineShapeOr"], 
     "EXTRA": ["inlineShapeOr"], 
     "PNAME_LN": ["inlineShapeOr"], 
     "PNAME_NS": ["inlineShapeOr"]}, 
  "inlineShapeNot" : {
     "(": ["?NOT","inlineShapeAtom"], 
     ".": ["?NOT","inlineShapeAtom"], 
     "LITERAL": ["?NOT","inlineShapeAtom"], 
     "IRI": ["?NOT","inlineShapeAtom"], 
     "BNODE": ["?NOT","inlineShapeAtom"], 
     "NONLITERAL": ["?NOT","inlineShapeAtom"], 
     "REGEXP": ["?NOT","inlineShapeAtom"], 
     "[": ["?NOT","inlineShapeAtom"], 
     "{": ["?NOT","inlineShapeAtom"], 
     "CLOSED": ["?NOT","inlineShapeAtom"], 
     "ATPNAME_LN": ["?NOT","inlineShapeAtom"], 
     "ATPNAME_NS": ["?NOT","inlineShapeAtom"], 
     "@": ["?NOT","inlineShapeAtom"], 
     "LENGTH": ["?NOT","inlineShapeAtom"], 
     "MINLENGTH": ["?NOT","inlineShapeAtom"], 
     "MAXLENGTH": ["?NOT","inlineShapeAtom"], 
     "IRI_REF": ["?NOT","inlineShapeAtom"], 
     "MININCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "MINEXCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "MAXINCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "MAXEXCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "TOTALDIGITS": ["?NOT","inlineShapeAtom"], 
     "FRACTIONDIGITS": ["?NOT","inlineShapeAtom"], 
     "EXTRA": ["?NOT","inlineShapeAtom"], 
     "PNAME_LN": ["?NOT","inlineShapeAtom"], 
     "PNAME_NS": ["?NOT","inlineShapeAtom"], 
     "NOT": ["?NOT","inlineShapeAtom"]}, 
  "inlineShapeOr" : {
     "NOT": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "(": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     ".": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "LITERAL": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "IRI": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "BNODE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "NONLITERAL": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "REGEXP": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "[": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "{": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "CLOSED": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "ATPNAME_LN": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "ATPNAME_NS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "@": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "LENGTH": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MINLENGTH": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MAXLENGTH": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "IRI_REF": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MININCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MINEXCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MAXINCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MAXEXCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "TOTALDIGITS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "FRACTIONDIGITS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "EXTRA": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "PNAME_LN": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "PNAME_NS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"]}, 
  "inlineShapeOrRef" : {
     "{": ["or([inlineShapeDefinition,shapeRef])"], 
     "CLOSED": ["or([inlineShapeDefinition,shapeRef])"], 
     "ATPNAME_LN": ["or([inlineShapeDefinition,shapeRef])"], 
     "ATPNAME_NS": ["or([inlineShapeDefinition,shapeRef])"], 
     "@": ["or([inlineShapeDefinition,shapeRef])"], 
     "EXTRA": ["or([inlineShapeDefinition,shapeRef])"]}, 
  "iri" : {
     "IRI_REF": ["or([IRI_REF,prefixedName])"], 
     "PNAME_LN": ["or([IRI_REF,prefixedName])"], 
     "PNAME_NS": ["or([IRI_REF,prefixedName])"]}, 
  "iriRange" : {
     "IRI_REF": ["iri","?[~,*exclusion]"], 
     "PNAME_LN": ["iri","?[~,*exclusion]"], 
     "PNAME_NS": ["iri","?[~,*exclusion]"]}, 
  "langString" : {
     "LANG_STRING_LITERAL1": ["LANG_STRING_LITERAL1"], 
     "LANG_STRING_LITERAL_LONG1": ["LANG_STRING_LITERAL_LONG1"], 
     "LANG_STRING_LITERAL2": ["LANG_STRING_LITERAL2"], 
     "LANG_STRING_LITERAL_LONG2": ["LANG_STRING_LITERAL_LONG2"]}, 
  "languageExclusion" : {
     ".": ["."]}, 
  "languageRange" : {
     "LANGTAG": ["LANGTAG","?[~,*languageExclusion]"], 
     "@": ["@","~","*languageExclusion"]}, 
  "litNodeConstraint" : {
     "LITERAL": ["LITERAL","*xsFacet"], 
     "IRI_REF": ["datatype","*xsFacet"], 
     "PNAME_LN": ["datatype","*xsFacet"], 
     "PNAME_NS": ["datatype","*xsFacet"], 
     "[": ["valueSet","*xsFacet"], 
     "MININCLUSIVE": ["+numericFacet"], 
     "MINEXCLUSIVE": ["+numericFacet"], 
     "MAXINCLUSIVE": ["+numericFacet"], 
     "MAXEXCLUSIVE": ["+numericFacet"], 
     "TOTALDIGITS": ["+numericFacet"], 
     "FRACTIONDIGITS": ["+numericFacet"]}, 
  "literal" : {
     "INTEGER": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "DECIMAL": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "DOUBLE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "true": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "false": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL_LONG1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL_LONG2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_LONG1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_LONG2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"]}, 
  "literalExclusion" : {
     ".": ["."]}, 
  "literalRange" : {
     "INTEGER": ["literal","?[~,*literalExclusion]"], 
     "DECIMAL": ["literal","?[~,*literalExclusion]"], 
     "DOUBLE": ["literal","?[~,*literalExclusion]"], 
     "true": ["literal","?[~,*literalExclusion]"], 
     "false": ["literal","?[~,*literalExclusion]"], 
     "LANG_STRING_LITERAL1": ["literal","?[~,*literalExclusion]"], 
     "LANG_STRING_LITERAL_LONG1": ["literal","?[~,*literalExclusion]"], 
     "LANG_STRING_LITERAL2": ["literal","?[~,*literalExclusion]"], 
     "LANG_STRING_LITERAL_LONG2": ["literal","?[~,*literalExclusion]"], 
     "STRING_LITERAL1": ["literal","?[~,*literalExclusion]"], 
     "STRING_LITERAL_LONG1": ["literal","?[~,*literalExclusion]"], 
     "STRING_LITERAL2": ["literal","?[~,*literalExclusion]"], 
     "STRING_LITERAL_LONG2": ["literal","?[~,*literalExclusion]"]}, 
  "nonLitNodeConstraint" : {
     "IRI": ["nonLiteralKind","*stringFacet"], 
     "BNODE": ["nonLiteralKind","*stringFacet"], 
     "NONLITERAL": ["nonLiteralKind","*stringFacet"], 
     "REGEXP": ["+stringFacet"], 
     "LENGTH": ["+stringFacet"], 
     "MINLENGTH": ["+stringFacet"], 
     "MAXLENGTH": ["+stringFacet"]}, 
  "nonLiteralKind" : {
     "IRI": ["IRI"], 
     "BNODE": ["BNODE"], 
     "NONLITERAL": ["NONLITERAL"]}, 
  "notStartAction" : {
     "start": ["or([startt,shapeExprDecl])"], 
     "IRI_REF": ["or([startt,shapeExprDecl])"], 
     "BLANK_NODE_LABEL": ["or([startt,shapeExprDecl])"], 
     "PNAME_LN": ["or([startt,shapeExprDecl])"], 
     "PNAME_NS": ["or([startt,shapeExprDecl])"]}, 
  "numericFacet" : {
     "MININCLUSIVE": ["numericRange","numericLiteral"], 
     "MINEXCLUSIVE": ["numericRange","numericLiteral"], 
     "MAXINCLUSIVE": ["numericRange","numericLiteral"], 
     "MAXEXCLUSIVE": ["numericRange","numericLiteral"], 
     "TOTALDIGITS": ["numericLength","INTEGER"], 
     "FRACTIONDIGITS": ["numericLength","INTEGER"]}, 
  "numericLength" : {
     "TOTALDIGITS": ["TOTALDIGITS"], 
     "FRACTIONDIGITS": ["FRACTIONDIGITS"]}, 
  "numericLiteral" : {
     "INTEGER": ["INTEGER"], 
     "DECIMAL": ["DECIMAL"], 
     "DOUBLE": ["DOUBLE"]}, 
  "numericRange" : {
     "MININCLUSIVE": ["MININCLUSIVE"], 
     "MINEXCLUSIVE": ["MINEXCLUSIVE"], 
     "MAXINCLUSIVE": ["MAXINCLUSIVE"], 
     "MAXEXCLUSIVE": ["MAXEXCLUSIVE"]}, 
  "oneOfTripleExpr" : {
     "$": ["groupTripleExpr"], 
     "(": ["groupTripleExpr"], 
     "&": ["groupTripleExpr"], 
     "RDF_TYPE": ["groupTripleExpr"], 
     "^": ["groupTripleExpr"], 
     "IRI_REF": ["groupTripleExpr"], 
     "PNAME_LN": ["groupTripleExpr"], 
     "PNAME_NS": ["groupTripleExpr"]}, 
  "or([CODE,%])" : {
     "CODE": ["CODE"], 
     "%": ["%"]}, 
  "or([IRI_REF,prefixedName])" : {
     "IRI_REF": ["IRI_REF"], 
     "PNAME_LN": ["prefixedName"], 
     "PNAME_NS": ["prefixedName"]}, 
  "or([PNAME_LN,PNAME_NS])" : {
     "PNAME_LN": ["PNAME_LN"], 
     "PNAME_NS": ["PNAME_NS"]}, 
  "or([baseDecl,prefixDecl,importDecl])" : {
     "BASE": ["baseDecl"], 
     "PREFIX": ["prefixDecl"], 
     "IMPORT": ["importDecl"]}, 
  "or([directive,notStartAction])" : {
     "BASE": ["directive"], 
     "PREFIX": ["directive"], 
     "IMPORT": ["directive"], 
     "start": ["notStartAction"], 
     "IRI_REF": ["notStartAction"], 
     "BLANK_NODE_LABEL": ["notStartAction"], 
     "PNAME_LN": ["notStartAction"], 
     "PNAME_NS": ["notStartAction"]}, 
  "or([extraPropertySet,CLOSED])" : {
     "EXTRA": ["extraPropertySet"], 
     "CLOSED": ["CLOSED"]}, 
  "or([inlineShapeDefinition,shapeRef])" : {
     "{": ["inlineShapeDefinition"], 
     "CLOSED": ["inlineShapeDefinition"], 
     "EXTRA": ["inlineShapeDefinition"], 
     "ATPNAME_LN": ["shapeRef"], 
     "ATPNAME_NS": ["shapeRef"], 
     "@": ["shapeRef"]}, 
  "or([iri,RDF_TYPE])" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"], 
     "RDF_TYPE": ["RDF_TYPE"]}, 
  "or([iri,blankNode])" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"], 
     "BLANK_NODE_LABEL": ["blankNode"]}, 
  "or([iri,literal,LANGTAG])" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"], 
     "INTEGER": ["literal"], 
     "DECIMAL": ["literal"], 
     "DOUBLE": ["literal"], 
     "true": ["literal"], 
     "false": ["literal"], 
     "LANG_STRING_LITERAL1": ["literal"], 
     "LANG_STRING_LITERAL_LONG1": ["literal"], 
     "LANG_STRING_LITERAL2": ["literal"], 
     "LANG_STRING_LITERAL_LONG2": ["literal"], 
     "STRING_LITERAL1": ["literal"], 
     "STRING_LITERAL_LONG1": ["literal"], 
     "STRING_LITERAL2": ["literal"], 
     "STRING_LITERAL_LONG2": ["literal"], 
     "LANGTAG": ["LANGTAG"]}, 
  "or([iri,literal])" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"], 
     "INTEGER": ["literal"], 
     "DECIMAL": ["literal"], 
     "DOUBLE": ["literal"], 
     "true": ["literal"], 
     "false": ["literal"], 
     "LANG_STRING_LITERAL1": ["literal"], 
     "LANG_STRING_LITERAL_LONG1": ["literal"], 
     "LANG_STRING_LITERAL2": ["literal"], 
     "LANG_STRING_LITERAL_LONG2": ["literal"], 
     "STRING_LITERAL1": ["literal"], 
     "STRING_LITERAL_LONG1": ["literal"], 
     "STRING_LITERAL2": ["literal"], 
     "STRING_LITERAL_LONG2": ["literal"]}, 
  "or([langString,[string,?[^^,datatype]]])" : {
     "LANG_STRING_LITERAL1": ["langString"], 
     "LANG_STRING_LITERAL_LONG1": ["langString"], 
     "LANG_STRING_LITERAL2": ["langString"], 
     "LANG_STRING_LITERAL_LONG2": ["langString"], 
     "STRING_LITERAL1": ["[string,?[^^,datatype]]"], 
     "STRING_LITERAL_LONG1": ["[string,?[^^,datatype]]"], 
     "STRING_LITERAL2": ["[string,?[^^,datatype]]"], 
     "STRING_LITERAL_LONG2": ["[string,?[^^,datatype]]"]}, 
  "or([notStartAction,startActions])" : {
     "start": ["notStartAction"], 
     "IRI_REF": ["notStartAction"], 
     "BLANK_NODE_LABEL": ["notStartAction"], 
     "PNAME_LN": ["notStartAction"], 
     "PNAME_NS": ["notStartAction"], 
     "%": ["startActions"]}, 
  "or([rdfLiteral,numericLiteral,booleanLiteral])" : {
     "LANG_STRING_LITERAL1": ["rdfLiteral"], 
     "LANG_STRING_LITERAL_LONG1": ["rdfLiteral"], 
     "LANG_STRING_LITERAL2": ["rdfLiteral"], 
     "LANG_STRING_LITERAL_LONG2": ["rdfLiteral"], 
     "STRING_LITERAL1": ["rdfLiteral"], 
     "STRING_LITERAL_LONG1": ["rdfLiteral"], 
     "STRING_LITERAL2": ["rdfLiteral"], 
     "STRING_LITERAL_LONG2": ["rdfLiteral"], 
     "INTEGER": ["numericLiteral"], 
     "DECIMAL": ["numericLiteral"], 
     "DOUBLE": ["numericLiteral"], 
     "true": ["booleanLiteral"], 
     "false": ["booleanLiteral"]}, 
  "or([shapeDefinition,shapeRef])" : {
     "{": ["shapeDefinition"], 
     "CLOSED": ["shapeDefinition"], 
     "EXTRA": ["shapeDefinition"], 
     "ATPNAME_LN": ["shapeRef"], 
     "ATPNAME_NS": ["shapeRef"], 
     "@": ["shapeRef"]}, 
  "or([shapeExpression,EXTERNAL])" : {
     "NOT": ["shapeExpression"], 
     "(": ["shapeExpression"], 
     ".": ["shapeExpression"], 
     "LITERAL": ["shapeExpression"], 
     "IRI": ["shapeExpression"], 
     "BNODE": ["shapeExpression"], 
     "NONLITERAL": ["shapeExpression"], 
     "REGEXP": ["shapeExpression"], 
     "[": ["shapeExpression"], 
     "{": ["shapeExpression"], 
     "CLOSED": ["shapeExpression"], 
     "ATPNAME_LN": ["shapeExpression"], 
     "ATPNAME_NS": ["shapeExpression"], 
     "@": ["shapeExpression"], 
     "LENGTH": ["shapeExpression"], 
     "MINLENGTH": ["shapeExpression"], 
     "MAXLENGTH": ["shapeExpression"], 
     "IRI_REF": ["shapeExpression"], 
     "MININCLUSIVE": ["shapeExpression"], 
     "MINEXCLUSIVE": ["shapeExpression"], 
     "MAXINCLUSIVE": ["shapeExpression"], 
     "MAXEXCLUSIVE": ["shapeExpression"], 
     "TOTALDIGITS": ["shapeExpression"], 
     "FRACTIONDIGITS": ["shapeExpression"], 
     "EXTRA": ["shapeExpression"], 
     "PNAME_LN": ["shapeExpression"], 
     "PNAME_NS": ["shapeExpression"], 
     "EXTERNAL": ["EXTERNAL"]}, 
  "or([startt,shapeExprDecl])" : {
     "start": ["startt"], 
     "IRI_REF": ["shapeExprDecl"], 
     "BLANK_NODE_LABEL": ["shapeExprDecl"], 
     "PNAME_LN": ["shapeExprDecl"], 
     "PNAME_NS": ["shapeExprDecl"]}, 
  "or([stringFacet,numericFacet])" : {
     "REGEXP": ["stringFacet"], 
     "LENGTH": ["stringFacet"], 
     "MINLENGTH": ["stringFacet"], 
     "MAXLENGTH": ["stringFacet"], 
     "MININCLUSIVE": ["numericFacet"], 
     "MINEXCLUSIVE": ["numericFacet"], 
     "MAXINCLUSIVE": ["numericFacet"], 
     "MAXEXCLUSIVE": ["numericFacet"], 
     "TOTALDIGITS": ["numericFacet"], 
     "FRACTIONDIGITS": ["numericFacet"]}, 
  "or([tripleConstraint,bracketedTripleExpr])" : {
     "RDF_TYPE": ["tripleConstraint"], 
     "^": ["tripleConstraint"], 
     "IRI_REF": ["tripleConstraint"], 
     "PNAME_LN": ["tripleConstraint"], 
     "PNAME_NS": ["tripleConstraint"], 
     "(": ["bracketedTripleExpr"]}, 
  "or([true,false])" : {
     "true": ["true"], 
     "false": ["false"]}, 
  "predicate" : {
     "RDF_TYPE": ["or([iri,RDF_TYPE])"], 
     "IRI_REF": ["or([iri,RDF_TYPE])"], 
     "PNAME_LN": ["or([iri,RDF_TYPE])"], 
     "PNAME_NS": ["or([iri,RDF_TYPE])"]}, 
  "prefixDecl" : {
     "PREFIX": ["PREFIX","PNAME_NS","IRI_REF"]}, 
  "prefixedName" : {
     "PNAME_LN": ["or([PNAME_LN,PNAME_NS])"], 
     "PNAME_NS": ["or([PNAME_LN,PNAME_NS])"]}, 
  "rdfLiteral" : {
     "LANG_STRING_LITERAL1": ["or([langString,[string,?[^^,datatype]]])"], 
     "LANG_STRING_LITERAL_LONG1": ["or([langString,[string,?[^^,datatype]]])"], 
     "LANG_STRING_LITERAL2": ["or([langString,[string,?[^^,datatype]]])"], 
     "LANG_STRING_LITERAL_LONG2": ["or([langString,[string,?[^^,datatype]]])"], 
     "STRING_LITERAL1": ["or([langString,[string,?[^^,datatype]]])"], 
     "STRING_LITERAL_LONG1": ["or([langString,[string,?[^^,datatype]]])"], 
     "STRING_LITERAL2": ["or([langString,[string,?[^^,datatype]]])"], 
     "STRING_LITERAL_LONG2": ["or([langString,[string,?[^^,datatype]]])"]}, 
  "semanticActions" : {
     "%": ["*codeDecl"], 
     "OR": ["*codeDecl"], 
     "AND": ["*codeDecl"], 
     "IRI": ["*codeDecl"], 
     "BNODE": ["*codeDecl"], 
     "NONLITERAL": ["*codeDecl"], 
     "REGEXP": ["*codeDecl"], 
     "LENGTH": ["*codeDecl"], 
     "MINLENGTH": ["*codeDecl"], 
     "MAXLENGTH": ["*codeDecl"], 
     ";": ["*codeDecl"], 
     ")": ["*codeDecl"], 
     "BASE": ["*codeDecl"], 
     "PREFIX": ["*codeDecl"], 
     "IMPORT": ["*codeDecl"], 
     "start": ["*codeDecl"], 
     "IRI_REF": ["*codeDecl"], 
     "BLANK_NODE_LABEL": ["*codeDecl"], 
     "PNAME_LN": ["*codeDecl"], 
     "PNAME_NS": ["*codeDecl"], 
     "$": ["*codeDecl"]}, 
  "senseFlags" : {
     "^": ["^"]}, 
  "shapeAnd" : {
     "NOT": ["shapeNot","*[AND,shapeNot]"], 
     "(": ["shapeNot","*[AND,shapeNot]"], 
     ".": ["shapeNot","*[AND,shapeNot]"], 
     "LITERAL": ["shapeNot","*[AND,shapeNot]"], 
     "IRI": ["shapeNot","*[AND,shapeNot]"], 
     "BNODE": ["shapeNot","*[AND,shapeNot]"], 
     "NONLITERAL": ["shapeNot","*[AND,shapeNot]"], 
     "REGEXP": ["shapeNot","*[AND,shapeNot]"], 
     "[": ["shapeNot","*[AND,shapeNot]"], 
     "{": ["shapeNot","*[AND,shapeNot]"], 
     "CLOSED": ["shapeNot","*[AND,shapeNot]"], 
     "ATPNAME_LN": ["shapeNot","*[AND,shapeNot]"], 
     "ATPNAME_NS": ["shapeNot","*[AND,shapeNot]"], 
     "@": ["shapeNot","*[AND,shapeNot]"], 
     "LENGTH": ["shapeNot","*[AND,shapeNot]"], 
     "MINLENGTH": ["shapeNot","*[AND,shapeNot]"], 
     "MAXLENGTH": ["shapeNot","*[AND,shapeNot]"], 
     "IRI_REF": ["shapeNot","*[AND,shapeNot]"], 
     "MININCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "MINEXCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "MAXINCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "MAXEXCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "TOTALDIGITS": ["shapeNot","*[AND,shapeNot]"], 
     "FRACTIONDIGITS": ["shapeNot","*[AND,shapeNot]"], 
     "EXTRA": ["shapeNot","*[AND,shapeNot]"], 
     "PNAME_LN": ["shapeNot","*[AND,shapeNot]"], 
     "PNAME_NS": ["shapeNot","*[AND,shapeNot]"]}, 
  "shapeAtom" : {
     "IRI": ["nonLitNodeConstraint","?shapeOrRef"], 
     "BNODE": ["nonLitNodeConstraint","?shapeOrRef"], 
     "NONLITERAL": ["nonLitNodeConstraint","?shapeOrRef"], 
     "REGEXP": ["nonLitNodeConstraint","?shapeOrRef"], 
     "LENGTH": ["nonLitNodeConstraint","?shapeOrRef"], 
     "MINLENGTH": ["nonLitNodeConstraint","?shapeOrRef"], 
     "MAXLENGTH": ["nonLitNodeConstraint","?shapeOrRef"], 
     "LITERAL": ["litNodeConstraint"], 
     "[": ["litNodeConstraint"], 
     "IRI_REF": ["litNodeConstraint"], 
     "MININCLUSIVE": ["litNodeConstraint"], 
     "MINEXCLUSIVE": ["litNodeConstraint"], 
     "MAXINCLUSIVE": ["litNodeConstraint"], 
     "MAXEXCLUSIVE": ["litNodeConstraint"], 
     "TOTALDIGITS": ["litNodeConstraint"], 
     "FRACTIONDIGITS": ["litNodeConstraint"], 
     "PNAME_LN": ["litNodeConstraint"], 
     "PNAME_NS": ["litNodeConstraint"], 
     "{": ["shapeOrRef","?nonLitNodeConstraint"], 
     "CLOSED": ["shapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_LN": ["shapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_NS": ["shapeOrRef","?nonLitNodeConstraint"], 
     "@": ["shapeOrRef","?nonLitNodeConstraint"], 
     "EXTRA": ["shapeOrRef","?nonLitNodeConstraint"], 
     "(": ["(","shapeExpression",")"], 
     ".": ["."]}, 
  "shapeDefinition" : {
     "{": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}","*annotation","semanticActions"], 
     "CLOSED": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}","*annotation","semanticActions"], 
     "EXTRA": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}","*annotation","semanticActions"]}, 
  "shapeExprDecl" : {
     "IRI_REF": ["shapeExprLabel","or([shapeExpression,EXTERNAL])"], 
     "BLANK_NODE_LABEL": ["shapeExprLabel","or([shapeExpression,EXTERNAL])"], 
     "PNAME_LN": ["shapeExprLabel","or([shapeExpression,EXTERNAL])"], 
     "PNAME_NS": ["shapeExprLabel","or([shapeExpression,EXTERNAL])"]}, 
  "shapeExprLabel" : {
     "IRI_REF": ["or([iri,blankNode])"], 
     "BLANK_NODE_LABEL": ["or([iri,blankNode])"], 
     "PNAME_LN": ["or([iri,blankNode])"], 
     "PNAME_NS": ["or([iri,blankNode])"]}, 
  "shapeExpression" : {
     "NOT": ["shapeOr"], 
     "(": ["shapeOr"], 
     ".": ["shapeOr"], 
     "LITERAL": ["shapeOr"], 
     "IRI": ["shapeOr"], 
     "BNODE": ["shapeOr"], 
     "NONLITERAL": ["shapeOr"], 
     "REGEXP": ["shapeOr"], 
     "[": ["shapeOr"], 
     "{": ["shapeOr"], 
     "CLOSED": ["shapeOr"], 
     "ATPNAME_LN": ["shapeOr"], 
     "ATPNAME_NS": ["shapeOr"], 
     "@": ["shapeOr"], 
     "LENGTH": ["shapeOr"], 
     "MINLENGTH": ["shapeOr"], 
     "MAXLENGTH": ["shapeOr"], 
     "IRI_REF": ["shapeOr"], 
     "MININCLUSIVE": ["shapeOr"], 
     "MINEXCLUSIVE": ["shapeOr"], 
     "MAXINCLUSIVE": ["shapeOr"], 
     "MAXEXCLUSIVE": ["shapeOr"], 
     "TOTALDIGITS": ["shapeOr"], 
     "FRACTIONDIGITS": ["shapeOr"], 
     "EXTRA": ["shapeOr"], 
     "PNAME_LN": ["shapeOr"], 
     "PNAME_NS": ["shapeOr"]}, 
  "shapeNot" : {
     "(": ["?NOT","shapeAtom"], 
     ".": ["?NOT","shapeAtom"], 
     "LITERAL": ["?NOT","shapeAtom"], 
     "IRI": ["?NOT","shapeAtom"], 
     "BNODE": ["?NOT","shapeAtom"], 
     "NONLITERAL": ["?NOT","shapeAtom"], 
     "REGEXP": ["?NOT","shapeAtom"], 
     "[": ["?NOT","shapeAtom"], 
     "{": ["?NOT","shapeAtom"], 
     "CLOSED": ["?NOT","shapeAtom"], 
     "ATPNAME_LN": ["?NOT","shapeAtom"], 
     "ATPNAME_NS": ["?NOT","shapeAtom"], 
     "@": ["?NOT","shapeAtom"], 
     "LENGTH": ["?NOT","shapeAtom"], 
     "MINLENGTH": ["?NOT","shapeAtom"], 
     "MAXLENGTH": ["?NOT","shapeAtom"], 
     "IRI_REF": ["?NOT","shapeAtom"], 
     "MININCLUSIVE": ["?NOT","shapeAtom"], 
     "MINEXCLUSIVE": ["?NOT","shapeAtom"], 
     "MAXINCLUSIVE": ["?NOT","shapeAtom"], 
     "MAXEXCLUSIVE": ["?NOT","shapeAtom"], 
     "TOTALDIGITS": ["?NOT","shapeAtom"], 
     "FRACTIONDIGITS": ["?NOT","shapeAtom"], 
     "EXTRA": ["?NOT","shapeAtom"], 
     "PNAME_LN": ["?NOT","shapeAtom"], 
     "PNAME_NS": ["?NOT","shapeAtom"], 
     "NOT": ["?NOT","shapeAtom"]}, 
  "shapeOr" : {
     "NOT": ["shapeAnd","*[OR,shapeAnd]"], 
     "(": ["shapeAnd","*[OR,shapeAnd]"], 
     ".": ["shapeAnd","*[OR,shapeAnd]"], 
     "LITERAL": ["shapeAnd","*[OR,shapeAnd]"], 
     "IRI": ["shapeAnd","*[OR,shapeAnd]"], 
     "BNODE": ["shapeAnd","*[OR,shapeAnd]"], 
     "NONLITERAL": ["shapeAnd","*[OR,shapeAnd]"], 
     "REGEXP": ["shapeAnd","*[OR,shapeAnd]"], 
     "[": ["shapeAnd","*[OR,shapeAnd]"], 
     "{": ["shapeAnd","*[OR,shapeAnd]"], 
     "CLOSED": ["shapeAnd","*[OR,shapeAnd]"], 
     "ATPNAME_LN": ["shapeAnd","*[OR,shapeAnd]"], 
     "ATPNAME_NS": ["shapeAnd","*[OR,shapeAnd]"], 
     "@": ["shapeAnd","*[OR,shapeAnd]"], 
     "LENGTH": ["shapeAnd","*[OR,shapeAnd]"], 
     "MINLENGTH": ["shapeAnd","*[OR,shapeAnd]"], 
     "MAXLENGTH": ["shapeAnd","*[OR,shapeAnd]"], 
     "IRI_REF": ["shapeAnd","*[OR,shapeAnd]"], 
     "MININCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "MINEXCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "MAXINCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "MAXEXCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "TOTALDIGITS": ["shapeAnd","*[OR,shapeAnd]"], 
     "FRACTIONDIGITS": ["shapeAnd","*[OR,shapeAnd]"], 
     "EXTRA": ["shapeAnd","*[OR,shapeAnd]"], 
     "PNAME_LN": ["shapeAnd","*[OR,shapeAnd]"], 
     "PNAME_NS": ["shapeAnd","*[OR,shapeAnd]"]}, 
  "shapeOrRef" : {
     "{": ["or([shapeDefinition,shapeRef])"], 
     "CLOSED": ["or([shapeDefinition,shapeRef])"], 
     "ATPNAME_LN": ["or([shapeDefinition,shapeRef])"], 
     "ATPNAME_NS": ["or([shapeDefinition,shapeRef])"], 
     "@": ["or([shapeDefinition,shapeRef])"], 
     "EXTRA": ["or([shapeDefinition,shapeRef])"]}, 
  "shapeRef" : {
     "ATPNAME_LN": ["ATPNAME_LN"], 
     "ATPNAME_NS": ["ATPNAME_NS"], 
     "@": ["@","shapeExprLabel"]}, 
  "shexDoC" : {
     "$": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "start": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "%": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "IRI_REF": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "BLANK_NODE_LABEL": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "PNAME_LN": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "PNAME_NS": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "BASE": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "PREFIX": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "IMPORT": ["*directive","?[or([notStartAction,startActions]),*statement]","$"]}, 
  "startActions" : {
     "%": ["+codeDecl"]}, 
  "startt" : {
     "start": ["start","=","inlineShapeExpression"]}, 
  "statement" : {
     "BASE": ["or([directive,notStartAction])"], 
     "PREFIX": ["or([directive,notStartAction])"], 
     "IMPORT": ["or([directive,notStartAction])"], 
     "start": ["or([directive,notStartAction])"], 
     "IRI_REF": ["or([directive,notStartAction])"], 
     "BLANK_NODE_LABEL": ["or([directive,notStartAction])"], 
     "PNAME_LN": ["or([directive,notStartAction])"], 
     "PNAME_NS": ["or([directive,notStartAction])"]}, 
  "string" : {
     "STRING_LITERAL1": ["STRING_LITERAL1"], 
     "STRING_LITERAL_LONG1": ["STRING_LITERAL_LONG1"], 
     "STRING_LITERAL2": ["STRING_LITERAL2"], 
     "STRING_LITERAL_LONG2": ["STRING_LITERAL_LONG2"]}, 
  "stringFacet" : {
     "LENGTH": ["stringLength","INTEGER"], 
     "MINLENGTH": ["stringLength","INTEGER"], 
     "MAXLENGTH": ["stringLength","INTEGER"], 
     "REGEXP": ["REGEXP"]}, 
  "stringLength" : {
     "LENGTH": ["LENGTH"], 
     "MINLENGTH": ["MINLENGTH"], 
     "MAXLENGTH": ["MAXLENGTH"]}, 
  "tripleConstraint" : {
     "RDF_TYPE": ["?senseFlags","predicate","inlineShapeExpression","?cardinality","*annotation","semanticActions"], 
     "IRI_REF": ["?senseFlags","predicate","inlineShapeExpression","?cardinality","*annotation","semanticActions"], 
     "PNAME_LN": ["?senseFlags","predicate","inlineShapeExpression","?cardinality","*annotation","semanticActions"], 
     "PNAME_NS": ["?senseFlags","predicate","inlineShapeExpression","?cardinality","*annotation","semanticActions"], 
     "^": ["?senseFlags","predicate","inlineShapeExpression","?cardinality","*annotation","semanticActions"]}, 
  "tripleExprLabel" : {
     "IRI_REF": ["or([iri,blankNode])"], 
     "BLANK_NODE_LABEL": ["or([iri,blankNode])"], 
     "PNAME_LN": ["or([iri,blankNode])"], 
     "PNAME_NS": ["or([iri,blankNode])"]}, 
  "tripleExpression" : {
     "$": ["oneOfTripleExpr"], 
     "(": ["oneOfTripleExpr"], 
     "&": ["oneOfTripleExpr"], 
     "RDF_TYPE": ["oneOfTripleExpr"], 
     "^": ["oneOfTripleExpr"], 
     "IRI_REF": ["oneOfTripleExpr"], 
     "PNAME_LN": ["oneOfTripleExpr"], 
     "PNAME_NS": ["oneOfTripleExpr"]}, 
  "unaryTripleExpr" : {
     "(": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "RDF_TYPE": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "^": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "IRI_REF": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "PNAME_LN": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "PNAME_NS": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "$": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "&": ["include"]}, 
  "valueSet" : {
     "[": ["[","*valueSetValue","]"]}, 
  "valueSetValue" : {
     "IRI_REF": ["iriRange"], 
     "PNAME_LN": ["iriRange"], 
     "PNAME_NS": ["iriRange"], 
     "INTEGER": ["literalRange"], 
     "DECIMAL": ["literalRange"], 
     "DOUBLE": ["literalRange"], 
     "true": ["literalRange"], 
     "false": ["literalRange"], 
     "LANG_STRING_LITERAL1": ["literalRange"], 
     "LANG_STRING_LITERAL_LONG1": ["literalRange"], 
     "LANG_STRING_LITERAL2": ["literalRange"], 
     "LANG_STRING_LITERAL_LONG2": ["literalRange"], 
     "STRING_LITERAL1": ["literalRange"], 
     "STRING_LITERAL_LONG1": ["literalRange"], 
     "STRING_LITERAL2": ["literalRange"], 
     "STRING_LITERAL_LONG2": ["literalRange"], 
     "LANGTAG": ["languageRange"], 
     "@": ["languageRange"]}, 
  "xsFacet" : {
     "REGEXP": ["or([stringFacet,numericFacet])"], 
     "LENGTH": ["or([stringFacet,numericFacet])"], 
     "MINLENGTH": ["or([stringFacet,numericFacet])"], 
     "MAXLENGTH": ["or([stringFacet,numericFacet])"], 
     "MININCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "MINEXCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "MAXINCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "MAXEXCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "TOTALDIGITS": ["or([stringFacet,numericFacet])"], 
     "FRACTIONDIGITS": ["or([stringFacet,numericFacet])"]}
},

keywords:/^(BASE|PREFIX|IMPORT|start|EXTERNAL|OR|AND|NOT|LITERAL|NONLITERAL|IRI|BNODE|LENGTH|MINLENGTH|MAXLENGTH|MININCLUSIVE|MINEXCLUSIVE|MAXINCLUSIVE|MAXEXCLUSIVE|TOTALDIGITS|FRACTIONDIGITS|CLOSED|EXTRA)/i ,

punct:/^(=|\(|\)|\.|@|\{|\}|\||;|$|\*|\+|\?|\^|\[|\]|-|\~|&|\/\/|%|\^\^)/ ,

startSymbol:"shexDoC",
acceptEmpty:true,
}