module.exports = {table:
{
  "*[;,unaryTripleExpr]" : {
     ";": ["[;,unaryTripleExpr]","*[;,unaryTripleExpr]"], 
     "|": [], 
     ";": [], 
     "}": []}, 
  "*[AND,inlineShapeNot]" : {
     "AND": ["[AND,inlineShapeNot]","*[AND,inlineShapeNot]"], 
     "=": [], 
     "OR": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*[AND,shapeNot]" : {
     "AND": ["[AND,shapeNot]","*[AND,shapeNot]"], 
     "OR": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*[OR,inlineShapeAnd]" : {
     "OR": ["[OR,inlineShapeAnd]","*[OR,inlineShapeAnd]"], 
     "=": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*[OR,shapeAnd]" : {
     "OR": ["[OR,shapeAnd]","*[OR,shapeAnd]"], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*annotation" : {
     "annotation": ["annotation","*annotation"], 
     "semanticActions": []}, 
  "*aux2" : {
     "|": ["aux2","*aux2"], 
     "}": []}, 
  "*codeDecl" : {
     "codeDecl": ["codeDecl","*codeDecl"], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*directive" : {
     "BASE": ["directive","*directive"], 
     "PREFIX": ["directive","*directive"], 
     "IMPORT": ["directive","*directive"], 
     "$": [], 
     "shapeExprLabel": [], 
     "codeDecl": []}, 
  "*numericFacet" : {
     "MININCLUSIVE": ["numericFacet","*numericFacet"], 
     "MINEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXINCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "TOTALDIGITS": ["numericFacet","*numericFacet"], 
     "FRACTIONDIGITS": ["numericFacet","*numericFacet"], 
     "OR": [], 
     "AND": [], 
     "=": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*or([extraPropertySet,CLOSED])" : {
     "CLOSED": ["or([extraPropertySet,CLOSED])","*or([extraPropertySet,CLOSED])"], 
     "EXTRA": ["or([extraPropertySet,CLOSED])","*or([extraPropertySet,CLOSED])"], 
     "{": []}, 
  "*predicate" : {
     "predicate": ["predicate","*predicate"], 
     "CLOSED": [], 
     "EXTRA": [], 
     "{": []}, 
  "*statement" : {
     "BASE": ["statement","*statement"], 
     "PREFIX": ["statement","*statement"], 
     "IMPORT": ["statement","*statement"], 
     "shapeExprLabel": ["statement","*statement"], 
     "$": []}, 
  "*stringFacet" : {
     "REGEXP": ["stringFacet","*stringFacet"], 
     "LENGTH": ["stringFacet","*stringFacet"], 
     "MINLENGTH": ["stringFacet","*stringFacet"], 
     "MAXLENGTH": ["stringFacet","*stringFacet"], 
     "OR": [], 
     "AND": [], 
     "{": [], 
     "CLOSED": [], 
     "ATPNAME_LN": [], 
     "ATPNAME_NS": [], 
     "@": [], 
     "EXTRA": [], 
     "=": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "*xsFacet" : {
     "REGEXP": ["xsFacet","*xsFacet"], 
     "LENGTH": ["xsFacet","*xsFacet"], 
     "MINLENGTH": ["xsFacet","*xsFacet"], 
     "MAXLENGTH": ["xsFacet","*xsFacet"], 
     "MININCLUSIVE": ["xsFacet","*xsFacet"], 
     "MINEXCLUSIVE": ["xsFacet","*xsFacet"], 
     "MAXINCLUSIVE": ["xsFacet","*xsFacet"], 
     "MAXEXCLUSIVE": ["xsFacet","*xsFacet"], 
     "TOTALDIGITS": ["xsFacet","*xsFacet"], 
     "FRACTIONDIGITS": ["xsFacet","*xsFacet"], 
     "OR": [], 
     "AND": [], 
     "=": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "+[;,unaryTripleExpr]" : {
     ";": ["[;,unaryTripleExpr]","*[;,unaryTripleExpr]"]}, 
  "+aux2" : {
     "|": ["aux2","*aux2"]}, 
  "+codeDecl" : {
     "codeDecl": ["codeDecl","*codeDecl"]}, 
  "+numericFacet" : {
     "MININCLUSIVE": ["numericFacet","*numericFacet"], 
     "MINEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXINCLUSIVE": ["numericFacet","*numericFacet"], 
     "MAXEXCLUSIVE": ["numericFacet","*numericFacet"], 
     "TOTALDIGITS": ["numericFacet","*numericFacet"], 
     "FRACTIONDIGITS": ["numericFacet","*numericFacet"]}, 
  "+predicate" : {
     "predicate": ["predicate","*predicate"]}, 
  "+stringFacet" : {
     "REGEXP": ["stringFacet","*stringFacet"], 
     "LENGTH": ["stringFacet","*stringFacet"], 
     "MINLENGTH": ["stringFacet","*stringFacet"], 
     "MAXLENGTH": ["stringFacet","*stringFacet"]}, 
  "?;" : {
     ";": [";"], 
     "|": [], 
     "}": []}, 
  "?NOT" : {
     "NOT": ["NOT"], 
     "(": [], 
     ".": [], 
     "LITERAL": [], 
     "datatype": [], 
     "valueSet": [], 
     "IRI": [], 
     "BNODE": [], 
     "NONLITERAL": [], 
     "REGEXP": [], 
     "{": [], 
     "CLOSED": [], 
     "ATPNAME_LN": [], 
     "ATPNAME_NS": [], 
     "@": [], 
     "LENGTH": [], 
     "MINLENGTH": [], 
     "MAXLENGTH": [], 
     "MININCLUSIVE": [], 
     "MINEXCLUSIVE": [], 
     "MAXINCLUSIVE": [], 
     "MAXEXCLUSIVE": [], 
     "TOTALDIGITS": [], 
     "FRACTIONDIGITS": [], 
     "EXTRA": []}, 
  "?[$,tripleExprLabel]" : {
     "$": ["[$,tripleExprLabel]"], 
     "tripleConstraint": [], 
     "bracketedTripleExpr": []}, 
  "?[or([notStartAction,startActions]),*statement]" : {
     "shapeExprLabel": ["[or([notStartAction,startActions]),*statement]"], 
     "codeDecl": ["[or([notStartAction,startActions]),*statement]"], 
     "$": []}, 
  "?inlineShapeOrRef" : {
     "{": ["inlineShapeOrRef"], 
     "CLOSED": ["inlineShapeOrRef"], 
     "ATPNAME_LN": ["inlineShapeOrRef"], 
     "ATPNAME_NS": ["inlineShapeOrRef"], 
     "@": ["inlineShapeOrRef"], 
     "EXTRA": ["inlineShapeOrRef"], 
     "=": [], 
     "OR": [], 
     "AND": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "?nonLitNodeConstraint" : {
     "IRI": ["nonLitNodeConstraint"], 
     "BNODE": ["nonLitNodeConstraint"], 
     "NONLITERAL": ["nonLitNodeConstraint"], 
     "REGEXP": ["nonLitNodeConstraint"], 
     "LENGTH": ["nonLitNodeConstraint"], 
     "MINLENGTH": ["nonLitNodeConstraint"], 
     "MAXLENGTH": ["nonLitNodeConstraint"], 
     "OR": [], 
     "AND": [], 
     "=": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "?shapeOrRef" : {
     "{": ["shapeOrRef"], 
     "CLOSED": ["shapeOrRef"], 
     "ATPNAME_LN": ["shapeOrRef"], 
     "ATPNAME_NS": ["shapeOrRef"], 
     "@": ["shapeOrRef"], 
     "EXTRA": ["shapeOrRef"], 
     "OR": [], 
     "AND": [], 
     ")": [], 
     "BASE": [], 
     "PREFIX": [], 
     "IMPORT": [], 
     "shapeExprLabel": [], 
     "$": []}, 
  "?tripleExpression" : {
     "tripleConstraint": ["tripleExpression"], 
     "bracketedTripleExpr": ["tripleExpression"], 
     "$": ["tripleExpression"], 
     "include": ["tripleExpression"], 
     "}": []}, 
  "[$,tripleExprLabel]" : {
     "$": ["$","tripleExprLabel"]}, 
  "[;,unaryTripleExpr]" : {
     ";": [";","unaryTripleExpr"]}, 
  "[AND,inlineShapeNot]" : {
     "AND": ["AND","inlineShapeNot"]}, 
  "[AND,shapeNot]" : {
     "AND": ["AND","shapeNot"]}, 
  "[OR,inlineShapeAnd]" : {
     "OR": ["OR","inlineShapeAnd"]}, 
  "[OR,shapeAnd]" : {
     "OR": ["OR","shapeAnd"]}, 
  "[or([notStartAction,startActions]),*statement]" : {
     "shapeExprLabel": ["or([notStartAction,startActions])","*statement"], 
     "codeDecl": ["or([notStartAction,startActions])","*statement"]}, 
  "aux" : {
     "tripleConstraint": ["groupTripleExpr"], 
     "bracketedTripleExpr": ["groupTripleExpr"], 
     "$": ["groupTripleExpr"], 
     "include": ["groupTripleExpr"]}, 
  "aux2" : {
     "|": ["|","groupTripleExpr"]}, 
  "baseDecl" : {
     "BASE": ["BASE","IRIREF"]}, 
  "directive" : {
     "BASE": ["or([baseDecl,prefixDecl,importDecl])"], 
     "PREFIX": ["or([baseDecl,prefixDecl,importDecl])"], 
     "IMPORT": ["or([baseDecl,prefixDecl,importDecl])"]}, 
  "extraPropertySet" : {
     "EXTRA": ["EXTRA","+predicate"]}, 
  "groupTripleExpr" : {
     "tripleConstraint": ["singleElementGroup"], 
     "bracketedTripleExpr": ["singleElementGroup"], 
     "$": ["singleElementGroup"], 
     "include": ["singleElementGroup"], 
     "tripleConstraint": ["multiElementGroup"], 
     "bracketedTripleExpr": ["multiElementGroup"], 
     "$": ["multiElementGroup"], 
     "include": ["multiElementGroup"]}, 
  "importDecl" : {
     "IMPORT": ["IMPORT","IRIREF"]}, 
  "inlineShapeAnd" : {
     "NOT": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "(": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     ".": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "LITERAL": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "datatype": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "valueSet": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "IRI": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "BNODE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "NONLITERAL": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "REGEXP": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "{": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "CLOSED": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "ATPNAME_LN": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "ATPNAME_NS": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "@": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "LENGTH": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MINLENGTH": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MAXLENGTH": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MININCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MINEXCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MAXINCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "MAXEXCLUSIVE": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "TOTALDIGITS": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "FRACTIONDIGITS": ["inlineShapeNot","*[AND,inlineShapeNot]"], 
     "EXTRA": ["inlineShapeNot","*[AND,inlineShapeNot]"]}, 
  "inlineShapeAtom" : {
     "IRI": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "BNODE": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "NONLITERAL": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "REGEXP": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "LENGTH": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "MINLENGTH": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "MAXLENGTH": ["nonLitNodeConstraint","?inlineShapeOrRef"], 
     "LITERAL": ["litNodeConstraint"], 
     "datatype": ["litNodeConstraint"], 
     "valueSet": ["litNodeConstraint"], 
     "MININCLUSIVE": ["litNodeConstraint"], 
     "MINEXCLUSIVE": ["litNodeConstraint"], 
     "MAXINCLUSIVE": ["litNodeConstraint"], 
     "MAXEXCLUSIVE": ["litNodeConstraint"], 
     "TOTALDIGITS": ["litNodeConstraint"], 
     "FRACTIONDIGITS": ["litNodeConstraint"], 
     "{": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "CLOSED": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_LN": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_NS": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "@": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "EXTRA": ["inlineShapeOrRef","?nonLitNodeConstraint"], 
     "(": ["(","shapeExpression",")"], 
     ".": ["."]}, 
  "inlineShapeDefinition" : {
     "{": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}"], 
     "CLOSED": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}"], 
     "EXTRA": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}"]}, 
  "inlineShapeExpression" : {
     "NOT": ["inlineShapeOr"], 
     "(": ["inlineShapeOr"], 
     ".": ["inlineShapeOr"], 
     "LITERAL": ["inlineShapeOr"], 
     "datatype": ["inlineShapeOr"], 
     "valueSet": ["inlineShapeOr"], 
     "IRI": ["inlineShapeOr"], 
     "BNODE": ["inlineShapeOr"], 
     "NONLITERAL": ["inlineShapeOr"], 
     "REGEXP": ["inlineShapeOr"], 
     "{": ["inlineShapeOr"], 
     "CLOSED": ["inlineShapeOr"], 
     "ATPNAME_LN": ["inlineShapeOr"], 
     "ATPNAME_NS": ["inlineShapeOr"], 
     "@": ["inlineShapeOr"], 
     "LENGTH": ["inlineShapeOr"], 
     "MINLENGTH": ["inlineShapeOr"], 
     "MAXLENGTH": ["inlineShapeOr"], 
     "MININCLUSIVE": ["inlineShapeOr"], 
     "MINEXCLUSIVE": ["inlineShapeOr"], 
     "MAXINCLUSIVE": ["inlineShapeOr"], 
     "MAXEXCLUSIVE": ["inlineShapeOr"], 
     "TOTALDIGITS": ["inlineShapeOr"], 
     "FRACTIONDIGITS": ["inlineShapeOr"], 
     "EXTRA": ["inlineShapeOr"]}, 
  "inlineShapeNot" : {
     "(": ["?NOT","inlineShapeAtom"], 
     ".": ["?NOT","inlineShapeAtom"], 
     "LITERAL": ["?NOT","inlineShapeAtom"], 
     "datatype": ["?NOT","inlineShapeAtom"], 
     "valueSet": ["?NOT","inlineShapeAtom"], 
     "IRI": ["?NOT","inlineShapeAtom"], 
     "BNODE": ["?NOT","inlineShapeAtom"], 
     "NONLITERAL": ["?NOT","inlineShapeAtom"], 
     "REGEXP": ["?NOT","inlineShapeAtom"], 
     "{": ["?NOT","inlineShapeAtom"], 
     "CLOSED": ["?NOT","inlineShapeAtom"], 
     "ATPNAME_LN": ["?NOT","inlineShapeAtom"], 
     "ATPNAME_NS": ["?NOT","inlineShapeAtom"], 
     "@": ["?NOT","inlineShapeAtom"], 
     "LENGTH": ["?NOT","inlineShapeAtom"], 
     "MINLENGTH": ["?NOT","inlineShapeAtom"], 
     "MAXLENGTH": ["?NOT","inlineShapeAtom"], 
     "MININCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "MINEXCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "MAXINCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "MAXEXCLUSIVE": ["?NOT","inlineShapeAtom"], 
     "TOTALDIGITS": ["?NOT","inlineShapeAtom"], 
     "FRACTIONDIGITS": ["?NOT","inlineShapeAtom"], 
     "EXTRA": ["?NOT","inlineShapeAtom"], 
     "NOT": ["?NOT","inlineShapeAtom"]}, 
  "inlineShapeOr" : {
     "NOT": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "(": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     ".": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "LITERAL": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "datatype": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "valueSet": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "IRI": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "BNODE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "NONLITERAL": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "REGEXP": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "{": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "CLOSED": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "ATPNAME_LN": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "ATPNAME_NS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "@": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "LENGTH": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MINLENGTH": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MAXLENGTH": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MININCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MINEXCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MAXINCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "MAXEXCLUSIVE": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "TOTALDIGITS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "FRACTIONDIGITS": ["inlineShapeAnd","*[OR,inlineShapeAnd]"], 
     "EXTRA": ["inlineShapeAnd","*[OR,inlineShapeAnd]"]}, 
  "inlineShapeOrRef" : {
     "{": ["or([inlineShapeDefinition,shapeRef])"], 
     "CLOSED": ["or([inlineShapeDefinition,shapeRef])"], 
     "ATPNAME_LN": ["or([inlineShapeDefinition,shapeRef])"], 
     "ATPNAME_NS": ["or([inlineShapeDefinition,shapeRef])"], 
     "@": ["or([inlineShapeDefinition,shapeRef])"], 
     "EXTRA": ["or([inlineShapeDefinition,shapeRef])"]}, 
  "litNodeConstraint" : {
     "LITERAL": ["LITERAL","*xsFacet"], 
     "datatype": ["datatype","*xsFacet"], 
     "valueSet": ["valueSet","*xsFacet"], 
     "MININCLUSIVE": ["+numericFacet"], 
     "MINEXCLUSIVE": ["+numericFacet"], 
     "MAXINCLUSIVE": ["+numericFacet"], 
     "MAXEXCLUSIVE": ["+numericFacet"], 
     "TOTALDIGITS": ["+numericFacet"], 
     "FRACTIONDIGITS": ["+numericFacet"]}, 
  "multiElementGroup" : {
     "tripleConstraint": ["unaryTripleExpr","+[;,unaryTripleExpr]","?;"], 
     "bracketedTripleExpr": ["unaryTripleExpr","+[;,unaryTripleExpr]","?;"], 
     "$": ["unaryTripleExpr","+[;,unaryTripleExpr]","?;"], 
     "include": ["unaryTripleExpr","+[;,unaryTripleExpr]","?;"]}, 
  "multiElementOneOf" : {
     "tripleConstraint": ["aux","+aux2"], 
     "bracketedTripleExpr": ["aux","+aux2"], 
     "$": ["aux","+aux2"], 
     "include": ["aux","+aux2"]}, 
  "nonLitNodeConstraint" : {
     "IRI": ["nonLiteralKind","*stringFacet"], 
     "BNODE": ["nonLiteralKind","*stringFacet"], 
     "NONLITERAL": ["nonLiteralKind","*stringFacet"], 
     "REGEXP": ["+stringFacet"], 
     "LENGTH": ["+stringFacet"], 
     "MINLENGTH": ["+stringFacet"], 
     "MAXLENGTH": ["+stringFacet"]}, 
  "nonLiteralKind" : {
     "IRI": ["IRI"], 
     "BNODE": ["BNODE"], 
     "NONLITERAL": ["NONLITERAL"]}, 
  "notStartAction" : {
     "shapeExprLabel": ["or([start,shapeExprDecl])"]}, 
  "numericFacet" : {
     "MININCLUSIVE": ["numericRange","numericLiteral"], 
     "MINEXCLUSIVE": ["numericRange","numericLiteral"], 
     "MAXINCLUSIVE": ["numericRange","numericLiteral"], 
     "MAXEXCLUSIVE": ["numericRange","numericLiteral"], 
     "TOTALDIGITS": ["numericLength","INTEGER"], 
     "FRACTIONDIGITS": ["numericLength","INTEGER"]}, 
  "numericLength" : {
     "TOTALDIGITS": ["TOTALDIGITS"], 
     "FRACTIONDIGITS": ["FRACTIONDIGITS"]}, 
  "numericRange" : {
     "MININCLUSIVE": ["MININCLUSIVE"], 
     "MINEXCLUSIVE": ["MINEXCLUSIVE"], 
     "MAXINCLUSIVE": ["MAXINCLUSIVE"], 
     "MAXEXCLUSIVE": ["MAXEXCLUSIVE"]}, 
  "oneOfTripleExpr" : {
     "tripleConstraint": ["groupTripleExpr"], 
     "bracketedTripleExpr": ["groupTripleExpr"], 
     "$": ["groupTripleExpr"], 
     "include": ["groupTripleExpr"], 
     "tripleConstraint": ["multiElementOneOf"], 
     "bracketedTripleExpr": ["multiElementOneOf"], 
     "$": ["multiElementOneOf"], 
     "include": ["multiElementOneOf"]}, 
  "or([baseDecl,prefixDecl,importDecl])" : {
     "BASE": ["baseDecl"], 
     "PREFIX": ["prefixDecl"], 
     "IMPORT": ["importDecl"]}, 
  "or([directive,notStartAction])" : {
     "BASE": ["directive"], 
     "PREFIX": ["directive"], 
     "IMPORT": ["directive"], 
     "shapeExprLabel": ["notStartAction"]}, 
  "or([extraPropertySet,CLOSED])" : {
     "EXTRA": ["extraPropertySet"], 
     "CLOSED": ["CLOSED"]}, 
  "or([inlineShapeDefinition,shapeRef])" : {
     "{": ["inlineShapeDefinition"], 
     "CLOSED": ["inlineShapeDefinition"], 
     "EXTRA": ["inlineShapeDefinition"], 
     "ATPNAME_LN": ["shapeRef"], 
     "ATPNAME_NS": ["shapeRef"], 
     "@": ["shapeRef"]}, 
  "or([notStartAction,startActions])" : {
     "shapeExprLabel": ["notStartAction"], 
     "codeDecl": ["startActions"]}, 
  "or([shapeDefinition,shapeRef])" : {
     "{": ["shapeDefinition"], 
     "CLOSED": ["shapeDefinition"], 
     "EXTRA": ["shapeDefinition"], 
     "ATPNAME_LN": ["shapeRef"], 
     "ATPNAME_NS": ["shapeRef"], 
     "@": ["shapeRef"]}, 
  "or([shapeExpression,EXTERNAL])" : {
     "NOT": ["shapeExpression"], 
     "(": ["shapeExpression"], 
     ".": ["shapeExpression"], 
     "LITERAL": ["shapeExpression"], 
     "datatype": ["shapeExpression"], 
     "valueSet": ["shapeExpression"], 
     "IRI": ["shapeExpression"], 
     "BNODE": ["shapeExpression"], 
     "NONLITERAL": ["shapeExpression"], 
     "REGEXP": ["shapeExpression"], 
     "{": ["shapeExpression"], 
     "CLOSED": ["shapeExpression"], 
     "ATPNAME_LN": ["shapeExpression"], 
     "ATPNAME_NS": ["shapeExpression"], 
     "@": ["shapeExpression"], 
     "LENGTH": ["shapeExpression"], 
     "MINLENGTH": ["shapeExpression"], 
     "MAXLENGTH": ["shapeExpression"], 
     "MININCLUSIVE": ["shapeExpression"], 
     "MINEXCLUSIVE": ["shapeExpression"], 
     "MAXINCLUSIVE": ["shapeExpression"], 
     "MAXEXCLUSIVE": ["shapeExpression"], 
     "TOTALDIGITS": ["shapeExpression"], 
     "FRACTIONDIGITS": ["shapeExpression"], 
     "EXTRA": ["shapeExpression"], 
     "EXTERNAL": ["EXTERNAL"]}, 
  "or([start,shapeExprDecl])" : {
     "shapeExprLabel": ["shapeExprDecl"]}, 
  "or([stringFacet,numericFacet])" : {
     "REGEXP": ["stringFacet"], 
     "LENGTH": ["stringFacet"], 
     "MINLENGTH": ["stringFacet"], 
     "MAXLENGTH": ["stringFacet"], 
     "MININCLUSIVE": ["numericFacet"], 
     "MINEXCLUSIVE": ["numericFacet"], 
     "MAXINCLUSIVE": ["numericFacet"], 
     "MAXEXCLUSIVE": ["numericFacet"], 
     "TOTALDIGITS": ["numericFacet"], 
     "FRACTIONDIGITS": ["numericFacet"]}, 
  "or([tripleConstraint,bracketedTripleExpr])" : {
     "tripleConstraint": ["tripleConstraint"], 
     "bracketedTripleExpr": ["bracketedTripleExpr"]}, 
  "prefixDecl" : {
     "PREFIX": ["PREFIX","PNAME_NS","IRIREF"]}, 
  "shapeAnd" : {
     "NOT": ["shapeNot","*[AND,shapeNot]"], 
     "(": ["shapeNot","*[AND,shapeNot]"], 
     ".": ["shapeNot","*[AND,shapeNot]"], 
     "LITERAL": ["shapeNot","*[AND,shapeNot]"], 
     "datatype": ["shapeNot","*[AND,shapeNot]"], 
     "valueSet": ["shapeNot","*[AND,shapeNot]"], 
     "IRI": ["shapeNot","*[AND,shapeNot]"], 
     "BNODE": ["shapeNot","*[AND,shapeNot]"], 
     "NONLITERAL": ["shapeNot","*[AND,shapeNot]"], 
     "REGEXP": ["shapeNot","*[AND,shapeNot]"], 
     "{": ["shapeNot","*[AND,shapeNot]"], 
     "CLOSED": ["shapeNot","*[AND,shapeNot]"], 
     "ATPNAME_LN": ["shapeNot","*[AND,shapeNot]"], 
     "ATPNAME_NS": ["shapeNot","*[AND,shapeNot]"], 
     "@": ["shapeNot","*[AND,shapeNot]"], 
     "LENGTH": ["shapeNot","*[AND,shapeNot]"], 
     "MINLENGTH": ["shapeNot","*[AND,shapeNot]"], 
     "MAXLENGTH": ["shapeNot","*[AND,shapeNot]"], 
     "MININCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "MINEXCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "MAXINCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "MAXEXCLUSIVE": ["shapeNot","*[AND,shapeNot]"], 
     "TOTALDIGITS": ["shapeNot","*[AND,shapeNot]"], 
     "FRACTIONDIGITS": ["shapeNot","*[AND,shapeNot]"], 
     "EXTRA": ["shapeNot","*[AND,shapeNot]"]}, 
  "shapeAtom" : {
     "IRI": ["nonLitNodeConstraint","?shapeOrRef"], 
     "BNODE": ["nonLitNodeConstraint","?shapeOrRef"], 
     "NONLITERAL": ["nonLitNodeConstraint","?shapeOrRef"], 
     "REGEXP": ["nonLitNodeConstraint","?shapeOrRef"], 
     "LENGTH": ["nonLitNodeConstraint","?shapeOrRef"], 
     "MINLENGTH": ["nonLitNodeConstraint","?shapeOrRef"], 
     "MAXLENGTH": ["nonLitNodeConstraint","?shapeOrRef"], 
     "LITERAL": ["litNodeConstraint"], 
     "datatype": ["litNodeConstraint"], 
     "valueSet": ["litNodeConstraint"], 
     "MININCLUSIVE": ["litNodeConstraint"], 
     "MINEXCLUSIVE": ["litNodeConstraint"], 
     "MAXINCLUSIVE": ["litNodeConstraint"], 
     "MAXEXCLUSIVE": ["litNodeConstraint"], 
     "TOTALDIGITS": ["litNodeConstraint"], 
     "FRACTIONDIGITS": ["litNodeConstraint"], 
     "{": ["shapeOrRef","?nonLitNodeConstraint"], 
     "CLOSED": ["shapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_LN": ["shapeOrRef","?nonLitNodeConstraint"], 
     "ATPNAME_NS": ["shapeOrRef","?nonLitNodeConstraint"], 
     "@": ["shapeOrRef","?nonLitNodeConstraint"], 
     "EXTRA": ["shapeOrRef","?nonLitNodeConstraint"], 
     "(": ["(","shapeExpression",")"], 
     ".": ["."]}, 
  "shapeDefinition" : {
     "{": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}","*annotation","semanticActions"], 
     "CLOSED": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}","*annotation","semanticActions"], 
     "EXTRA": ["*or([extraPropertySet,CLOSED])","{","?tripleExpression","}","*annotation","semanticActions"]}, 
  "shapeExprDecl" : {
     "shapeExprLabel": ["shapeExprLabel","or([shapeExpression,EXTERNAL])"]}, 
  "shapeExpression" : {
     "NOT": ["shapeOr"], 
     "(": ["shapeOr"], 
     ".": ["shapeOr"], 
     "LITERAL": ["shapeOr"], 
     "datatype": ["shapeOr"], 
     "valueSet": ["shapeOr"], 
     "IRI": ["shapeOr"], 
     "BNODE": ["shapeOr"], 
     "NONLITERAL": ["shapeOr"], 
     "REGEXP": ["shapeOr"], 
     "{": ["shapeOr"], 
     "CLOSED": ["shapeOr"], 
     "ATPNAME_LN": ["shapeOr"], 
     "ATPNAME_NS": ["shapeOr"], 
     "@": ["shapeOr"], 
     "LENGTH": ["shapeOr"], 
     "MINLENGTH": ["shapeOr"], 
     "MAXLENGTH": ["shapeOr"], 
     "MININCLUSIVE": ["shapeOr"], 
     "MINEXCLUSIVE": ["shapeOr"], 
     "MAXINCLUSIVE": ["shapeOr"], 
     "MAXEXCLUSIVE": ["shapeOr"], 
     "TOTALDIGITS": ["shapeOr"], 
     "FRACTIONDIGITS": ["shapeOr"], 
     "EXTRA": ["shapeOr"]}, 
  "shapeNot" : {
     "(": ["?NOT","shapeAtom"], 
     ".": ["?NOT","shapeAtom"], 
     "LITERAL": ["?NOT","shapeAtom"], 
     "datatype": ["?NOT","shapeAtom"], 
     "valueSet": ["?NOT","shapeAtom"], 
     "IRI": ["?NOT","shapeAtom"], 
     "BNODE": ["?NOT","shapeAtom"], 
     "NONLITERAL": ["?NOT","shapeAtom"], 
     "REGEXP": ["?NOT","shapeAtom"], 
     "{": ["?NOT","shapeAtom"], 
     "CLOSED": ["?NOT","shapeAtom"], 
     "ATPNAME_LN": ["?NOT","shapeAtom"], 
     "ATPNAME_NS": ["?NOT","shapeAtom"], 
     "@": ["?NOT","shapeAtom"], 
     "LENGTH": ["?NOT","shapeAtom"], 
     "MINLENGTH": ["?NOT","shapeAtom"], 
     "MAXLENGTH": ["?NOT","shapeAtom"], 
     "MININCLUSIVE": ["?NOT","shapeAtom"], 
     "MINEXCLUSIVE": ["?NOT","shapeAtom"], 
     "MAXINCLUSIVE": ["?NOT","shapeAtom"], 
     "MAXEXCLUSIVE": ["?NOT","shapeAtom"], 
     "TOTALDIGITS": ["?NOT","shapeAtom"], 
     "FRACTIONDIGITS": ["?NOT","shapeAtom"], 
     "EXTRA": ["?NOT","shapeAtom"], 
     "NOT": ["?NOT","shapeAtom"]}, 
  "shapeOr" : {
     "NOT": ["shapeAnd","*[OR,shapeAnd]"], 
     "(": ["shapeAnd","*[OR,shapeAnd]"], 
     ".": ["shapeAnd","*[OR,shapeAnd]"], 
     "LITERAL": ["shapeAnd","*[OR,shapeAnd]"], 
     "datatype": ["shapeAnd","*[OR,shapeAnd]"], 
     "valueSet": ["shapeAnd","*[OR,shapeAnd]"], 
     "IRI": ["shapeAnd","*[OR,shapeAnd]"], 
     "BNODE": ["shapeAnd","*[OR,shapeAnd]"], 
     "NONLITERAL": ["shapeAnd","*[OR,shapeAnd]"], 
     "REGEXP": ["shapeAnd","*[OR,shapeAnd]"], 
     "{": ["shapeAnd","*[OR,shapeAnd]"], 
     "CLOSED": ["shapeAnd","*[OR,shapeAnd]"], 
     "ATPNAME_LN": ["shapeAnd","*[OR,shapeAnd]"], 
     "ATPNAME_NS": ["shapeAnd","*[OR,shapeAnd]"], 
     "@": ["shapeAnd","*[OR,shapeAnd]"], 
     "LENGTH": ["shapeAnd","*[OR,shapeAnd]"], 
     "MINLENGTH": ["shapeAnd","*[OR,shapeAnd]"], 
     "MAXLENGTH": ["shapeAnd","*[OR,shapeAnd]"], 
     "MININCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "MINEXCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "MAXINCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "MAXEXCLUSIVE": ["shapeAnd","*[OR,shapeAnd]"], 
     "TOTALDIGITS": ["shapeAnd","*[OR,shapeAnd]"], 
     "FRACTIONDIGITS": ["shapeAnd","*[OR,shapeAnd]"], 
     "EXTRA": ["shapeAnd","*[OR,shapeAnd]"]}, 
  "shapeOrRef" : {
     "{": ["or([shapeDefinition,shapeRef])"], 
     "CLOSED": ["or([shapeDefinition,shapeRef])"], 
     "ATPNAME_LN": ["or([shapeDefinition,shapeRef])"], 
     "ATPNAME_NS": ["or([shapeDefinition,shapeRef])"], 
     "@": ["or([shapeDefinition,shapeRef])"], 
     "EXTRA": ["or([shapeDefinition,shapeRef])"]}, 
  "shapeRef" : {
     "ATPNAME_LN": ["ATPNAME_LN"], 
     "ATPNAME_NS": ["ATPNAME_NS"], 
     "@": ["@","shapeExprLabel"]}, 
  "shexDoC" : {
     "$": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "shapeExprLabel": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "codeDecl": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "BASE": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "PREFIX": ["*directive","?[or([notStartAction,startActions]),*statement]","$"], 
     "IMPORT": ["*directive","?[or([notStartAction,startActions]),*statement]","$"]}, 
  "singleElementGroup" : {
     "tripleConstraint": ["unaryTripleExpr"], 
     "bracketedTripleExpr": ["unaryTripleExpr"], 
     "$": ["unaryTripleExpr"], 
     "include": ["unaryTripleExpr"]}, 
  "start" : }, 
  "startActions" : {
     "codeDecl": ["+codeDecl"]}, 
  "statement" : {
     "BASE": ["or([directive,notStartAction])"], 
     "PREFIX": ["or([directive,notStartAction])"], 
     "IMPORT": ["or([directive,notStartAction])"], 
     "shapeExprLabel": ["or([directive,notStartAction])"]}, 
  "stringFacet" : {
     "LENGTH": ["stringLength","INTEGER"], 
     "MINLENGTH": ["stringLength","INTEGER"], 
     "MAXLENGTH": ["stringLength","INTEGER"], 
     "REGEXP": ["REGEXP"]}, 
  "stringLength" : {
     "LENGTH": ["LENGTH"], 
     "MINLENGTH": ["MINLENGTH"], 
     "MAXLENGTH": ["MAXLENGTH"]}, 
  "tripleExpression" : {
     "tripleConstraint": ["oneOfTripleExpr"], 
     "bracketedTripleExpr": ["oneOfTripleExpr"], 
     "$": ["oneOfTripleExpr"], 
     "include": ["oneOfTripleExpr"]}, 
  "unaryTripleExpr" : {
     "tripleConstraint": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "bracketedTripleExpr": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "$": ["?[$,tripleExprLabel]","or([tripleConstraint,bracketedTripleExpr])"], 
     "include": ["include"]}, 
  "xsFacet" : {
     "REGEXP": ["or([stringFacet,numericFacet])"], 
     "LENGTH": ["or([stringFacet,numericFacet])"], 
     "MINLENGTH": ["or([stringFacet,numericFacet])"], 
     "MAXLENGTH": ["or([stringFacet,numericFacet])"], 
     "MININCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "MINEXCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "MAXINCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "MAXEXCLUSIVE": ["or([stringFacet,numericFacet])"], 
     "TOTALDIGITS": ["or([stringFacet,numericFacet])"], 
     "FRACTIONDIGITS": ["or([stringFacet,numericFacet])"]}
},

keywords:/^(BASE|PREFIX|IMPORT|EXTERNAL|OR|AND|NOT|LITERAL|NONLITERAL|IRI|BNODE|LENGTH|MINLENGTH|MAXLENGTH|MININCLUSIVE|MINEXCLUSIVE|MAXINCLUSIVE|MAXEXCLUSIVE|TOTALDIGITS|FRACTIONDIGITS|CLOSED|EXTRA)/i ,

punct:/^(=|\(|\)|\.|@|\{|\}|\||;|$|\*|\+|\?|\^|\[|\]|-|\~|&|//|%|\^\^)/ ,

startSymbol:"shexDoC",
acceptEmpty:true,
}